#!/usr/bin/env bash
# shellcheck source=/dev/null
# shellcheck disable=SC2034,SC2154,SC2153,SC2119,SC2120,SC1090
# (variables, assignments and function calls span the sourced lib/ modules, so
#  cross-module references are invisible to per-file analysis)
# TinkerGame library module -- sourced by the "tinkergame" entry point. Do not execute directly.

# systemd user units that refresh Non-Steam artwork whenever Steam rewrites
# 'shortcuts.vdf', with a daily timer as a fallback for changes made while the
# units were not running. Installed and removed via 'artwork watch'; turning
# them on and off afterwards is plain 'systemctl --user'.

TGWATCHUNIT="${PROGNAME,,}-artwork"

function tgWatchUnitDir {
	printf '%s' "${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
}

function tgWatchShortcutPaths {
	if [ -z "$SUSDA" ]; then
		setSteamPaths
	fi

	# One line per Steam account. TinkerGame itself only ever resolves the most
	# recently logged in user, so watching that account alone would leave the
	# units blind after an account switch. The file need not exist yet -- systemd
	# then watches the closest existing parent directory instead.
	local TGW_UCFG
	local TGW_FOUND=0
	for TGW_UCFG in "$SUSDA"/*/config; do
		if [ -d "$TGW_UCFG" ]; then
			printf '%s\n' "$TGW_UCFG/$SCVDF"
			TGW_FOUND=1
		fi
	done

	[ "$TGW_FOUND" -eq 1 ]
}

function tgWatchWriteUnits {
	local TGW_DIR="$1"
	local -a TGW_PATHS=()
	mapfile -t TGW_PATHS < <(tgWatchShortcutPaths)

	if [ "${#TGW_PATHS[@]}" -eq 0 ]; then
		writelog "ERROR" "${FUNCNAME[0]} - No Steam user directory below '${SUSDA:-unset}' - cannot tell which '$SCVDF' to watch" "E"
		return 1
	fi

	# A unit with an empty or unusable ExecStart would be accepted by systemd and
	# then fail on every trigger, so refuse to write one in the first place
	if [ -z "$TG_ENTRYPOINT" ] || [ ! -x "$TG_ENTRYPOINT" ]; then
		writelog "ERROR" "${FUNCNAME[0]} - Cannot resolve the TinkerGame executable ('${TG_ENTRYPOINT:-unset}') - not writing units that would never start" "E"
		return 1
	fi

	mkProjDir "$TGW_DIR"
	if [ ! -d "$TGW_DIR" ]; then
		writelog "ERROR" "${FUNCNAME[0]} - Cannot create the systemd user unit directory '$TGW_DIR'" "E"
		return 1
	fi

	# ${PROGNAME,,} rather than $PROGCMD: the unit outlives the invocation that
	# wrote it, so the hint must not depend on how TinkerGame happened to be called
	local TGW_STAMP="# Generated by $PROGNAME $PROGVERS - '${PROGNAME,,} artwork watch uninstall' removes this file"

	{
		printf '%s\n' "$TGW_STAMP"
		# The run itself needs no GUI, but TinkerGame's dependency check probes yad,
		# and a user manager that starts before the desktop hands it a DISPLAY that
		# points at nothing yet. yad then fails, its version reads back empty, and
		# the whole run aborts with "Yad version '' is too old" on every boot.
		printf '[Unit]\nDescription=Update Steam artwork for Non-Steam games\nAfter=graphical-session.target\n\n'
		# Type=oneshot also debounces: while a run is in progress systemd will not
		# start a second one, so a burst of shortcut writes collapses into one refresh.
		# KillMode=process: the run may leave a notification waiting for the user.
		# The default would kill it together with the service the moment the run ends.
		printf '[Service]\nType=oneshot\nKillMode=process\nExecStart=%s artwork watch run\n' "$TG_ENTRYPOINT"
	} > "$TGW_DIR/${TGWATCHUNIT}.service"

	{
		printf '%s\n' "$TGW_STAMP"
		printf '[Unit]\nDescription=Watch Steam shortcuts for new Non-Steam games\n\n'
		printf '[Path]\n'
		local TGW_P
		for TGW_P in "${TGW_PATHS[@]}"; do
			printf 'PathChanged=%s\n' "$TGW_P"
		done
		# graphical-session.target, not default.target: the trigger only ever fires
		# while someone is logged in and Steam is writing, and a run before the
		# session exists cannot notify anyone anyway
		printf '\n[Install]\nWantedBy=graphical-session.target\n'
	} > "$TGW_DIR/${TGWATCHUNIT}.path"

	{
		printf '%s\n' "$TGW_STAMP"
		printf '[Unit]\nDescription=Refresh Steam artwork for Non-Steam games regularly\n\n'
		# Persistent so a machine that was off at the scheduled time still catches up
		printf '[Timer]\nOnCalendar=daily\nPersistent=true\n\n'
		# Also tied to the session, so the Persistent= catch-up lands once the
		# desktop is up rather than during boot
		printf '[Install]\nWantedBy=graphical-session.target\n'
	} > "$TGW_DIR/${TGWATCHUNIT}.timer"

	# Redirections above fail silently without 'set -e'; an incomplete unit set is
	# worse than none, because 'systemctl enable' would then fail with a confusing error
	local TGW_SUFFIX
	for TGW_SUFFIX in service path timer; do
		if [ ! -s "$TGW_DIR/${TGWATCHUNIT}.${TGW_SUFFIX}" ]; then
			writelog "ERROR" "${FUNCNAME[0]} - Failed to write '$TGW_DIR/${TGWATCHUNIT}.${TGW_SUFFIX}'" "E"
			return 1
		fi
	done

	writelog "INFO" "${FUNCNAME[0]} - Wrote '$TGWATCHUNIT' units to '$TGW_DIR', watching ${#TGW_PATHS[@]} '$SCVDF' location(s)"
	return 0
}

function tgWatchInstall {
	local TGW_DIR
	TGW_DIR="$(tgWatchUnitDir)"

	if ! tgWatchWriteUnits "$TGW_DIR"; then
		return 1
	fi

	if ! command -v "$SYSTEMCTL" > /dev/null 2>&1; then
		writelog "WARN" "${FUNCNAME[0]} - '$SYSTEMCTL' not found - units are in '$TGW_DIR' but could not be enabled" "E"
		return 1
	fi

	"$SYSTEMCTL" --user daemon-reload
	"$SYSTEMCTL" --user enable --now "${TGWATCHUNIT}.path" "${TGWATCHUNIT}.timer"

	writelog "INFO" "${FUNCNAME[0]} - Artwork watcher enabled - 'systemctl --user disable --now ${TGWATCHUNIT}.path ${TGWATCHUNIT}.timer' turns it off again" "E"
	return 0
}

function tgWatchUninstall {
	local TGW_DIR
	TGW_DIR="$(tgWatchUnitDir)"

	if command -v "$SYSTEMCTL" > /dev/null 2>&1; then
		"$SYSTEMCTL" --user disable --now "${TGWATCHUNIT}.path" "${TGWATCHUNIT}.timer" 2>/dev/null
	fi

	local TGW_SUFFIX
	for TGW_SUFFIX in path service timer; do
		if [ -f "$TGW_DIR/${TGWATCHUNIT}.${TGW_SUFFIX}" ]; then
			rm -f "$TGW_DIR/${TGWATCHUNIT}.${TGW_SUFFIX}"
			writelog "INFO" "${FUNCNAME[0]} - Removed '$TGW_DIR/${TGWATCHUNIT}.${TGW_SUFFIX}'"
		fi
	done

	if command -v "$SYSTEMCTL" > /dev/null 2>&1; then
		"$SYSTEMCTL" --user daemon-reload
	fi

	writelog "INFO" "${FUNCNAME[0]} - Artwork watcher removed" "E"
	return 0
}
